import mongoose from "mongoose"

const billingItemSchema = new mongoose.Schema({
  productId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "products",
    required: true
  },
  name: {
    type: String,
    required: true
  },
  price: {
    type: Number,
    required: true
  },
  quantity: {
    type: Number,
    required: true,
    min: 1
  },
  gstRate: {
    type: Number,
    default: 0
  }
}, { _id: false })

const billingSchema = new mongoose.Schema({
  billId: {
    type: String,
    unique: true,
    required: false // Will be auto-generated by pre-save hook
  },
  customerName: {
    type: String,
    default: "Customer"
  },
  items: {
    type: [billingItemSchema],
    required: true
  },
  billAmount: {
    type: Number,
    required: true,
    min: 0
  },
  userPaid: {
    type: Number,
    default: 0,
    min: 0
  },
  userDue: {
    type: Number,
    default: 0,
    min: 0
  },
  gst: {
    type: Boolean,
    default: false
  },
  gstPercent: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  totalAmount: {
    type: Number,
    required: true,
    min: 0
  },
  isDebit: {
    type: Boolean,
    default: false
  },
  status: {
    type: String,
    enum: ["completed", "due", "draft"],
    default: "draft"
  }
}, {
  timestamps: true
})

// Pre-save hook to generate billId (BLI00001 format)
billingSchema.pre("save", async function(next) {
  // Always generate billId if it doesn't exist
  if (!this.billId) {
    try {
      // Use the collection directly to avoid circular dependency
      const collection = this.constructor.db.collection("billings")
      const lastBill = await collection.findOne(
        {},
        { sort: { createdAt: -1 } }
      )
      
      let nextNumber = 1
      if (lastBill && lastBill.billId) {
        // Extract number from billId (e.g., BLI00001 -> 1)
        const match = lastBill.billId.match(/\d+/)
        if (match) {
          nextNumber = parseInt(match[0], 10) + 1
        }
      }
      
      // Format as BLI00001 (8 characters total: BLI + 5 digits)
      this.billId = `BLI${String(nextNumber).padStart(5, "0")}`
    } catch (error) {
      // If collection doesn't exist or error, start from 1
      this.billId = `BLI${String(1).padStart(5, "0")}`
    }
  }
  next()
})

export default mongoose.model("billing", billingSchema)

